In [26]:
import pandas as pd
from sklearn import datasets
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB, GaussianNB
import numpy as np
import matplotlib.pyplot as plt

from pprint import pprint

# Gensim
import gensim, spacy, logging, warnings
import gensim.corpora as corpora
from gensim.utils import simple_preprocess
from gensim.models import CoherenceModel
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# NLTK Stop words
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopWords_nltk = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /Users/lisun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [27]:
df = pd.read_csv('tripadvisor_hotel_reviews.csv')
df

Review  Rating
0      nice hotel expensive parking got good deal sta...       4
1      ok nothing special charge diamond member hilto...       2
2      nice rooms not 4* experience hotel monaco seat...       3
3      unique, great stay, wonderful time hotel monac...       5
4      great stay great stay, went seahawk game aweso...       5
...                                                  ...     ...
20486  best kept secret 3rd time staying charm, not 5...       5
20487  great location price view hotel great quick pl...       4
20488  ok just looks nice modern outside, desk staff ...       2
20489  hotel theft ruined vacation hotel opened sept ...       1
20490  people talking, ca n't believe excellent ratin...       2

[20491 rows x 2 columns]

In [28]:
#will use only the first 1,000 rows
df_1000 = df[0:1000]

In [29]:
corpus = "Hello there,There is,There is Hello,There is there,Is there Hello,Hello there is"

In [31]:
vectorizer = CountVectorizer(stop_words = 'english')
doc_term = vectorizer.fit_transform(corpus)

doc_term.shape

ValueError: Iterable over raw text documents expected, string object received.

In [32]:
tv = TfidfVectorizer(stop_words='english', ngram_range=(1,2), max_df = 0.9, min_df = 6)
tv_doc_term = tv.fit_transform(df.Review)
tv_doc_term2 = tv.transform(df.Review)
tfidf = pd.DataFrame(tv_doc_term.toarray(), columns = tv.get_feature_names())
tfidf

00  00 00  00 10  00 12  00 15  00 30  00 breakfast  00 charge  \
0      0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
1      0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
2      0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
3      0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
4      0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
...    ...    ...    ...    ...    ...    ...           ...        ...   
20486  0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
20487  0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
20488  0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
20489  0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
20490  0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   

       00 check  00 day  ...  zoo station  zoologischer  zoologischer garten  \
0           0.0     0.0  ...          0.0           0.0                  0.0   
1           0.0     0.0  ...          0.0           0.0                  0.0   
2           0.0     0.0  ...          0.0           0.0                  0.0   
3           0.0     0.0  ...          0.0           0.0                  0.0   
4           0.0     0.0  ...          0.0           0.0                  0.0   
...         ...     ...  ...          ...           ...                  ...   
20486       0.0     0.0  ...          0.0           0.0                  0.0   
20487       0.0     0.0  ...          0.0           0.0                  0.0   
20488       0.0     0.0  ...          0.0           0.0                  0.0   
20489       0.0     0.0  ...          0.0           0.0                  0.0   
20490       0.0     0.0  ...          0.0           0.0                  0.0   

       zurich  äcor   äe  äes   äs   ù_   ùn  
0         0.0   0.0  0.0  0.0  0.0  0.0  0.0  
1         0.0   0.0  0.0  0.0  0.0  0.0  0.0  
2         0.0   0.0  0.0  0.0  0.0  0.0  0.0  
3         0.0   0.0  0.0  0.0  0.0  0.0  0.0  
4         0.0   0.0  0.0  0.0  0.0  0.0  0.0  
...       ...   ...  ...  ...  ...  ...  ...  
20486     0.0   0.0  0.0  0.0  0.0  0.0  0.0  
20487     0.0   0.0  0.0  0.0  0.0  0.0  0.0  
20488     0.0   0.0  0.0  0.0  0.0  0.0  0.0  
20489     0.0   0.0  0.0  0.0  0.0  0.0  0.0  
20490     0.0   0.0  0.0  0.0  0.0  0.0  0.0  

[20491 rows x 55138 columns]

In [33]:
doc_term_df = pd.DataFrame(tv_doc_term.toarray(), columns=tv.get_feature_names())
doc_term_df

00  00 00  00 10  00 12  00 15  00 30  00 breakfast  00 charge  \
0      0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
1      0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
2      0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
3      0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
4      0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
...    ...    ...    ...    ...    ...    ...           ...        ...   
20486  0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
20487  0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
20488  0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
20489  0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   
20490  0.0    0.0    0.0    0.0    0.0    0.0           0.0        0.0   

       00 check  00 day  ...  zoo station  zoologischer  zoologischer garten  \
0           0.0     0.0  ...          0.0           0.0                  0.0   
1           0.0     0.0  ...          0.0           0.0                  0.0   
2           0.0     0.0  ...          0.0           0.0                  0.0   
3           0.0     0.0  ...          0.0           0.0                  0.0   
4           0.0     0.0  ...          0.0           0.0                  0.0   
...         ...     ...  ...          ...           ...                  ...   
20486       0.0     0.0  ...          0.0           0.0                  0.0   
20487       0.0     0.0  ...          0.0           0.0                  0.0   
20488       0.0     0.0  ...          0.0           0.0                  0.0   
20489       0.0     0.0  ...          0.0           0.0                  0.0   
20490       0.0     0.0  ...          0.0           0.0                  0.0   

       zurich  äcor   äe  äes   äs   ù_   ùn  
0         0.0   0.0  0.0  0.0  0.0  0.0  0.0  
1         0.0   0.0  0.0  0.0  0.0  0.0  0.0  
2         0.0   0.0  0.0  0.0  0.0  0.0  0.0  
3         0.0   0.0  0.0  0.0  0.0  0.0  0.0  
4         0.0   0.0  0.0  0.0  0.0  0.0  0.0  
...       ...   ...  ...  ...  ...  ...  ...  
20486     0.0   0.0  0.0  0.0  0.0  0.0  0.0  
20487     0.0   0.0  0.0  0.0  0.0  0.0  0.0  
20488     0.0   0.0  0.0  0.0  0.0  0.0  0.0  
20489     0.0   0.0  0.0  0.0  0.0  0.0  0.0  
20490     0.0   0.0  0.0  0.0  0.0  0.0  0.0  

[20491 rows x 55138 columns]

In [35]:
from sklearn.decomposition import NMF

nmf = NMF(4, init = "nndsvda")
nmf.fit(tv_doc_term)
nmf

NMF(init='nndsvda', n_components=4)

In [36]:
topic_term = nmf.components_.round(3)
topic_term.shape

(4, 55138)

In [37]:
topic_term_df = pd.DataFrame(topic_term.round(3),
                index = ["component_1", "component_2", "component_3", "component_4"], #"component_5"], #"component_6", "component_7"],
                columns = tv.get_feature_names())
topic_term_df

00  00 00  00 10  00 12  00 15  00 30  00 breakfast  \
component_1  0.000  0.000  0.000  0.000  0.000  0.000         0.002   
component_2  0.094  0.005  0.001  0.001  0.001  0.004         0.000   
component_3  0.113  0.002  0.001  0.001  0.001  0.002         0.001   
component_4  0.000  0.000  0.000  0.000  0.000  0.000         0.001   

             00 charge  00 check  00 day  ...  zoo station  zoologischer  \
component_1      0.000     0.000   0.000  ...        0.000         0.000   
component_2      0.001     0.001   0.005  ...        0.000         0.000   
component_3      0.001     0.001   0.007  ...        0.000         0.000   
component_4      0.000     0.000   0.000  ...        0.008         0.003   

             zoologischer garten  zurich   äcor     äe    äes     äs     ù_  \
component_1                0.000   0.000  0.000  0.001  0.000  0.000  0.000   
component_2                0.000   0.000  0.000  0.001  0.000  0.001  0.002   
component_3                0.000   0.000  0.004  0.000  0.000  0.001  0.004   
component_4                0.003   0.003  0.004  0.001  0.004  0.004  0.000   

                ùn  
component_1  0.000  
component_2  0.001  
component_3  0.000  
component_4  0.001  

[4 rows x 55138 columns]

In [38]:
# Function to display the top n terms in each topic
def display_topics(model, feature_names, no_top_words, topic_names = None): 
    for ix, topic in enumerate(model.components_):
        if not topic_names or not topic_names[ix]:
            print("\nTopic ", ix + 1)
        else:
            print("\nTopic: ", topic_names[ix])
        print(", ".join([feature_names[i]
                        for i in topic.argsort()[:-no_top_words - 1:-1]]))
    print("\n")
    return model, feature_names, no_top_words

In [39]:
output = display_topics(nmf, tv.get_feature_names(), 20)
### END SOLUTION
output;


Topic  1
great, hotel, location, stay, staff, great location, friendly, helpful, great hotel, hotel great, wonderful, stayed, place, loved, rooms, perfect, clean, fantastic, comfortable, recommend

Topic  2
resort, beach, food, pool, did, people, good, time, beautiful, day, water, just, vacation, great, cana, punta, punta cana, like, went, buffet

Topic  3
room, did, hotel, night, desk, bed, stay, service, floor, check, view, day, like, bathroom, told, got, booked, nice, just, asked

Topic  4
hotel, good, walk, breakfast, station, excellent, clean, location, city, nice, rooms, value, metro, area, located, small, barcelona, modern, staff, helpful




In [40]:
doc_topic = nmf.transform(tv_doc_term)

In [42]:
doc_topic.shape

(20491, 4)

In [43]:
doc_topic[0]

array([0.01296712, 0.        , 0.05664696, 0.00921348])

In [44]:
observation_interest = doc_topic[0]

In [45]:
from scipy import spatial

cosine_list=[]
for i in doc_topic: 
    result = 1 - spatial.distance.cosine(observation_interest, i)
    cosine_list.append(result)

In [46]:
rec = np.argsort(cosine_list)[-5:]
print(rec)

[10205  5743  6411 19605     0]


In [47]:
doc_topic[0:9]

array([[0.01296712, 0.        , 0.05664696, 0.00921348],
       [0.00169693, 0.        , 0.07674909, 0.0067265 ],
       [0.00634319, 0.        , 0.07767842, 0.        ],
       [0.03280837, 0.00089271, 0.02124819, 0.01418377],
       [0.0169593 , 0.01601278, 0.04796944, 0.00140428],
       [0.01382615, 0.00964231, 0.03294824, 0.00334988],
       [0.01591399, 0.        , 0.02553843, 0.02858833],
       [0.02496651, 0.01044393, 0.01678578, 0.00674949],
       [0.01972399, 0.        , 0.02508705, 0.00909828]])